version: "3.7"

services:
  postgres_db:
    image: postgres:12
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  django_backend:
    build: ./backend
    command: python /backend/code/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/backend/code
    ports:
      - 8000:8000
    depends_on:
      - postgres_db

  frontend:
    build: ./frontend
    command: npm start
    volumes:
      - ./frontend:/frontend/code
      - frontend/code/node_modules
    ports:
      - "3000:3000"
    stdin_open: true
    depends_on:
      - django_backend

volumes:
  postgres_data:
